import net.darkhax.curseforgegradle.TaskPublishCurseForge

plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '1.0.21'
    id 'net.darkhax.curseforgegradle' version '1.1.26'
    id "com.modrinth.minotaur" version '2.+'
}

tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
}

version = "$minecraft_version-$mod_loader-$mod_version"
group = mod_group_id

repositories {
    mavenLocal()

    maven { url "https://maven.shedaniel.me/" }
}

base {
    archivesName.set("${mod_file_name}")
}

java.toolchain.languageVersion = JavaLanguageVersion.of(java_version)

neoForge {
    version = project.neo_version

    parchment {
        mappingsVersion = project.parchment_mappings_version
        minecraftVersion = project.parchment_minecraft_version
    }

    accessTransformers = project.files('src/main/resources/META-INF/accesstransformer.cfg')

    runs {
        client {
            client()

            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        server {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        gameTestServer {
            type = "gameTestServer"
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        data {
            data()

            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }

        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'

            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

dependencies {
    implementation("me.shedaniel.cloth:cloth-config-neoforge:${cloth_config_version}")
}

var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neo_version            : neo_version,
            neo_version_range      : neo_version_range,
            loader_version_range   : loader_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
            mod_authors            : mod_authors,
            mod_logo               : mod_logo,
            mod_url                : mod_url,
            mod_issue_url          : mod_issue_url,
            mod_description        : mod_description,
            cloth_config_version   : cloth_config_version
    ]
    inputs.properties replaceProperties
    expand replaceProperties
    from "src/main/templates"
    into "build/generated/sources/modMetadata"
}

sourceSets.main.resources.srcDir generateModMetadata
neoForge.ideSyncTask generateModMetadata

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/repo"
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}

tasks.register ('printGitReleaseTitle') {
    doLast {
        println("${mod_file_name}-${version}")
    }
}

tasks.register ('printGitTag') {
    doLast {
        println("v${mod_version}-mc${minecraft_version}-${mod_loader.toLowerCase()}")
    }
}

def changelogFile = file("$project.rootDir/CHANGELOG.md")

if (System.getenv("CURSEFORGE_TOKEN") && changelogFile.exists ()) {
    tasks.register ('curseforge', TaskPublishCurseForge) {
        apiToken = System.getenv("CURSEFORGE_TOKEN")

        def mainFile = upload ('1020415', jar)
        mainFile.releaseType = 'release'
        mainFile.addModLoader ("$mod_loader")
        mainFile.addGameVersion ("$minecraft_version")
        mainFile.addJavaVersion ("Java $java_version")
        mainFile.addEnvironment ('Server', 'Client')

        mainFile.changelog = changelogFile
        mainFile.changelogType = 'markdown'

        mainFile.addRequirement ('cloth-config')
        mainFile.addOptional ('catalogue')
    }
}

if (System.getenv("MODRINTH_TOKEN") && changelogFile.exists ()) {
    modrinth {
        token = System.getenv("MODRINTH_TOKEN")
        projectId = "3fmH6nwV"
        versionNumber = "$mod_version+$minecraft_version-${mod_loader.toLowerCase()}"
        uploadFile = jar
        changelog = changelogFile.text
        versionName = "$mod_file_name $version"
        gameVersions = [minecraft_version]
        loaders = [mod_loader]

        dependencies {
            required.version "cloth-config", "${cloth_config_version}+${mod_loader.toLowerCase()}"
        }
    }
}
