import net.darkhax.curseforgegradle.TaskPublishCurseForge

plugins {
    id 'fabric-loom' version '1.6-SNAPSHOT'
    id 'maven-publish'
    id 'net.darkhax.curseforgegradle' version '1.1.26'
    id "com.modrinth.minotaur" version '2.+'
}

version = "$minecraft_version-$mod_loader-$mod_version"
group = project.maven_group

base {
    archivesName = "${project.archives_base_name}"
}

repositories {
    maven { url "https://maven.shedaniel.me/" }
    maven { url "https://maven.terraformersmc.com/releases/" }

    maven {
        name = "Terraformers"
        url = "https://maven.terraformersmc.com/"
    }
}

loom {
    mixin {
        defaultRefmapName = "${project.mod_id}.refmap.json"
    }

    accessWidenerPath = file("src/main/resources/${project.mod_id}.accesswidener")
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

    modApi("me.shedaniel.cloth:cloth-config-fabric:${project.cloth_config_version}") {
        exclude(group: "net.fabricmc.fabric-api")
    }

    modImplementation("com.terraformersmc:modmenu:${project.modmenu_version}")
}

processResources {
    inputs.property "version", project.version
    inputs.property "minecraft_version", project.minecraft_version
    inputs.property "loader_version", project.loader_version
    filteringCharset "UTF-8"

    filesMatching("fabric.mod.json") {
        expand "version": project.version,
                "minecraft_version": project.minecraft_version,
                "maven_group": project.maven_group,
                "loader_version": project.loader_version,
                "mod_id": project.mod_id,
                "fabric_api_version": project.fabric_api_version,
                "cloth_config_version": project.cloth_config_version
    }
}

def targetJavaVersion = 21
tasks.withType(JavaCompile).configureEach {
    it.options.encoding = "UTF-8"
    if (targetJavaVersion >= 10 || JavaVersion.current().isJava10Compatible()) {
        it.options.release.set(targetJavaVersion)
    }
}

java {
    def javaVersion = JavaVersion.toVersion(targetJavaVersion)
    if (JavaVersion.current() < javaVersion) {
        toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }
    withSourcesJar()
}

jar {
    from("LICENSE")
}

publishing {
    publications {
        create("mavenJava", MavenPublication) {
            artifactId = project.archives_base_name
            from components.java
        }
    }

    repositories {

    }
}

tasks.register ('printGitReleaseTitle') {
    doLast {
        println("${archives_base_name}-${version}")
    }
}

tasks.register ('printGitTag') {
    doLast {
        println("v${mod_version}-mc${minecraft_version}-${mod_loader.toLowerCase()}")
    }
}

def changelogFile = file("$project.rootDir/CHANGELOG.md")

if (System.getenv("CURSEFORGE_TOKEN") && changelogFile.exists ()) {
    tasks.register ('curseforge', TaskPublishCurseForge) {
        apiToken = System.getenv("CURSEFORGE_TOKEN")

        def mainFile = upload ('1020415', remapJar)
        mainFile.releaseType = 'release'
        mainFile.addModLoader ("$mod_loader")
        mainFile.addGameVersion ("$minecraft_version")
        mainFile.addJavaVersion ("Java $targetJavaVersion")
        mainFile.addEnvironment ('Server', 'Client')

        mainFile.changelog = changelogFile
        mainFile.changelogType = 'markdown'

        mainFile.addRequirement ('fabric-api')
        mainFile.addRequirement ('cloth-config')
        mainFile.addOptional ('catalogue')
        mainFile.addOptional ('modmenu')
    }
}

if (System.getenv("MODRINTH_TOKEN") && changelogFile.exists ()) {
    modrinth {
        token = System.getenv("MODRINTH_TOKEN")
        projectId = "3fmH6nwV"
        versionNumber = "$mod_version+$minecraft_version-$mod_loader"
        uploadFile = remapJar
        changelog = changelogFile.text
        versionName = "$archives_base_name $version"
        gameVersions = [minecraft_version]
        loaders = [mod_loader]

        dependencies {
            required.version "fabric-api", "${fabric_api_version}"
            required.version "cloth-config", "${cloth_config_version}+${mod_loader.toLowerCase()}"
            optional.project "modmenu"
        }
    }
}
