org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

java_version=21
minecraft_version=1.20.6
minecraft_version_range=[1.20.6,1.21)
forge_version=50.1.0
forge_version_range=[50,)
loader_version_range=[50,)
mod_loader=Forge
mapping_channel=official
mapping_version=1.20.6

mod_id=protection_enchantments
mod_name=Item Protection Enchantments
mod_file_name=ItemProtectionEnchantments
mod_license=LGPL-3.0
mod_version=1.0.4
mod_group_id=com.torikun9971
mod_authors=Torikun9971
mod_logo=icon.png
mod_url=https://github.com/Torikun9971/Item-Protection-Enchantments
mod_issue_url=https://github.com/Torikun9971/Item-Protection-Enchantments/issues
mod_description=Adds enchantments to protect items

cloth_config_version=14.0.139