org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

java_version=17
minecraft_version=1.18.2
minecraft_version_range=[1.18.2,1.19)
forge_version=40.2.0
forge_version_range=[40,)
loader_version_range=[40,)
mod_loader=Forge
mapping_channel=official
mapping_version=1.18.2

mod_id=protection_enchantments
mod_name=Item Protection Enchantments
mod_file_name=ItemProtectionEnchantments
mod_license=LGPL-3.0
mod_version=1.0.4
mod_group_id=com.torikun9971
mod_authors=Torikun9971
mod_logo=icon.png
mod_url=https://github.com/Torikun9971/Item-Protection-Enchantments
mod_issue_url=https://github.com/Torikun9971/Item-Protection-Enchantments/issues
mod_description=Adds enchantments to protect items

cloth_config_version=6.5.102