org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

java_version=21
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.13
minecraft_version=1.21.1
minecraft_version_range=[1.21.1, 1.22)
neo_version=21.1.92
neo_version_range=[21.1.0,)
loader_version_range=[4,)
mod_loader=NeoForge

mod_id=protection_enchantments
mod_name=Item Protection Enchantments
mod_file_name=ItemProtectionEnchantments
mod_license=LGPL-3.0
mod_version=1.0.4
mod_group_id=com.torikun9971
mod_authors=Torikun9971
mod_logo=icon.png
mod_url=https://github.com/Torikun9971/Item-Protection-Enchantments
mod_issue_url=https://github.com/Torikun9971/Item-Protection-Enchantments/issues
mod_description=Adds enchantments to protect items

cloth_config_version=15.0.140