name: release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Check out Repository
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: gradle

      - name: Grant execute permission for Gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Fetch Changelog from main branch
        run: |
          git fetch origin main
          git checkout origin/main -- CHANGELOG.md

      - name: Release on Modrinth, CurseForge, and GitHub
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: item-protection-enchantments
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          curseforge-id: 1020415
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          github-token: ${{ secrets.GITHUB_TOKEN }}